### ISSUE TITLE
Go reactive / webflux

### ISSUE THREAD

**Issue by napstr** [FredBoat/Backend#2]
Reasons:
it's 2018

Prerequisites:

- [ ] Springfox 3.x
  Springfox documentation does not work with webflux at all. _3.x should also bring OAS v3._
  Related PR: https://github.com/springfox/springfox/pull/2233

- [ ] Reactive database drivers (this will very likely not work with hibernate), or a threadpool to run requests in a blocking fashion.
  Possible candidates (I'm throwing everything that calls itself even in the slightest way async / reactive in here):
  - https://github.com/vert-x3/vertx-jdbc-client
  - https://github.com/vert-x3/vertx-mysql-postgresql-client
  - https://github.com/reactiverse/reactive-pg-client
  - https://github.com/jklingsporn/vertx-jooq
  - https://github.com/mauricio/postgresql-async
  - https://github.com/scalikejdbc/scalikejdbc-async
  - https://github.com/davidmoten/rxjava-jdbc

**Comment by Frederikam** [comment]
I'm normally an advocate for using Reactor, but this looks like a lot of trouble and I frankly don't see the problem it solves.

**Comment by napstr** [comment]
fred plz its 2018

**Comment by napstr** [comment]
I agree the reasons are a bit thin on this one.

**Comment by SuhanKoh** [comment]
How about rxjava? https://github.com/davidmoten/rxjava-jdbc (no hibernate support though)
